name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
 func-workflow: hjgraca/demo1/.github/workflows/deploy-az-func.yml@main

jobs:
  Build:
    uses: hjgraca/demo1/.github/workflows/build.yml@main
  
  Review:
    needs: Build
    if: github.event_name == 'pull_request'
    uses: ${{ env.func-workflow }}
    with:
      environment: dev
      function-name: empowering-partners-pt-dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      APP_SETTINGS: '${{ secrets.APP_SETTINGS }}'
        
  Staging:
    uses: ${{ env.func-workflow }}
    needs: Build
    if: github.event.ref == 'refs/heads/main'
    with:
      environment: staging
      function-name: empowering-partners-pt-stage
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      APP_SETTINGS: '${{ secrets.APP_SETTINGS }}' 
        
  Production:
    needs: Staging
    if: github.event.ref == 'refs/heads/main'
    uses: ${{ env.func-workflow }}
    with:
      environment: production
      function-name: empowering-partners-pt-prod
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      APP_SETTINGS: '${{ secrets.APP_SETTINGS }}' 
