name: deploy azure function

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      function-name:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      APP_SETTINGS:
        required: true
jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ steps.fa.outputs.app-url }}/api/hello
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
        
    - uses: actions/download-artifact@v2
      with:
        name: binary

    - name: "Azure Login"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ inputs.function-name }}
        app-settings-json: '${{ secrets.APP_SETTINGS }}' 
        
    - name: 'Azure Functions Deploy'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ inputs.function-name }}
        package: ${{ github.workspace }}
